### ISSUE TITLE
Feature-request: Shortcuts to minimize and restore window

### ISSUE THREAD

**Issue by 0x4a** [jdckr/todotxt.net#2]
Hi @jdckr,
great work with this fork :+1:

I'd like to suggest two features:

* minimizing (to tray if set so) the window with ESC button
* a shortcut to restore the tray-minimized window.

If I run the executable a second time (via autohotkey) it does not open from tray. If you could it make so that it re-opens the window when the application is already running in background and is executed again, that would be enough for me. Minimizing on ESC can be forced via autohotkey...

Regards, Daniel

**Comment by jdckr** [comment]
Hi @0x4a,
thanks for the request!

Unfortunately I am very limited in time within the next month that's why I will only spent time on features that are valuable for myself. Furthermore the intention of this fork was to add features that improve my workflow and make it more fun to use (dark mode). I never had the plan to create a release or to continue maintaining a successor of todotxt.net. I only did the release because you guys asked :-)

But nevertheless feel free to submit a PR. I am willing to merge it.

Cheers

**Comment by 0x4a** [comment]
Nevermind, was worth the try ;-)

I am not a .NET-Dev myself unfortunately, but maybe I can get restore-from-tray to work with autohotkey too,I'll see...

**Comment by jdckr** [comment]
Feature not planned. PR is still welcome.

**Comment by aubreyz** [comment]
This is GREAT. Please keep working on this fork.
